# Generated by Django 3.2 on 2021-04-18 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 18, 17, 12, 37, 165226, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 4, 18, 17, 12, 50, 813138, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
